version: '2'
services:
  web:
      image: nginx:latest
      ports:
          - "8880:80"
      volumes:
          - ./activerules:/var/www/html
          - ./site.conf:/etc/nginx/conf.d/default.conf
          - /data/cache:/var/www/html/cache
      links:
          - php
  php:
      image: bwinkers/docker-php7-phalcon
      volumes:
          - ./activerules:/var/www/html
          - /data/cache:/var/www/html/cache
      links:
          - postgres
  postgres:
    image: postgres
    restart: always
    environment:
        POSTGRES_PASSWORD: FZrtTASY8e3jmwjkK
        POSTGRES_USER: activerules
        POSTGRES_DB: activerules
    volumes:
          - /data/postgresql:/var/lib/postgresql/data
  adminer:
      image: adminer
      restart: always
      ports:
          - 8881:8080
      links:
        - postgres
  logger:
      image: gliderlabs/logspout
      ports:
          - "8882:80"
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock        